name: Build and Publish

on:
  push:
    branches: ["add_step_to_workflow"]
    
#on:
#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]

jobs:
  if_merged_build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Java version
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Replace database connection keys
        run: |
          cd src/main/resources
          json_file="liftlife-b89d1-firebase-adminsdk-1v4ox-c62b51cb58.json"
          key_id="${{ secrets.DB_KEY_ID }}"
          key="${{ secrets.DB_KEY }}"
          sed -i 's/"var1"/"$key_id"/g' $json_file
          sed -i 's/"var1"/"$key"/g' $json_file
          cat liftlife-b89d1-firebase-adminsdk-1v4ox-c62b51cb58.json
        shell: bash

      - name: Build Maven Image
        run: mvn clean package

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/microservices:liftlife-service

      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:liftlife-service
