name: Build and Publish

on:
  pull_request:
    branches: ["main"]
    types:
      - closed
#on:
#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]

jobs:
  if_merged_build-and-push-docker-image:
    if: github.event.pull_request.merged == true
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Setup Java version
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Maven Image
        run: mvn clean package

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/microservices:liftlife-service

      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:liftlife-service
